# Generated by Django 5.1 on 2024-08-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customuser_address_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
