# Generated by Django 5.1 on 2024-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customuser_is_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='papel',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor'), ('ESTOQUISTA', 'Estoquista')], default='CLIENTE', max_length=20),
        ),
    ]
